# Titel
title: Jekyll VNG Realisatie theme

#auteur
author: VNG Realisatie

#plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: text
    span:
      default_lang: text
      line_numbers: false
    block:
      default_lang: text
      # line_numbers: false
      # start_line: 1

collections:
  pages:
    output: true
  content:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: content
    values:
      layout: default

sass:
  load_paths:
    - _sass

github: VNG-Realisatie/
