# Titel
title: Jekyll VNG Realisatie theme

#auteur
author: VNG Realisatie

#plugins
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

markdown: kramdown

kramdown:
  parse_block_html: true

collections:
  pages:
    output: true
  content:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: default
  - scope:
      path: ''
      type: content
    values:
      layout: default

sass:
  load_paths:
    - _sass

github: VNG-Realisatie/
